version: "3"

services:
  app:
    build:
      context: .
    command: >
      sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python manage.py starter --username admin --password Admin123! --noinput --email admin@gmail.com && python3 manage.py wait_for_db && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
volumes:
  postgres_data: