# Generated by Django 4.2 on 2025-01-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task", name="status", field=models.BooleanField(default=False),
        ),
    ]
