# Generated by Django 4.2 on 2025-01-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
